### PR TITLE
fix install.sh

### LINKED ISSUE #1: Unable to install pylings through Poetry
Hello, I've tried to run the install command for Poetry provided in the README, but the `install.sh` script  didn't finish the execution correctly, here's my output:

```bash
❯ curl -L https://raw.githubusercontent.com/aless10/pylings/main/install.sh | bash

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3747  100  3747    0     0  14133      0 --:--:-- --:--:-- --:--:-- 14467
Let's get you set up with pylings!
Checking requirements...
SUCCESS: Git is installed
SUCCESS: python is installed
Checking python 'installer'...
bash: line 28: $1: unbound variable
```

After a little digging I found out that the `Installer` parameter ($1) wasn't passed in the command provided.
I then tried providing `poetry` as parameter in the commend like following:
```bash
curl -L https://raw.githubusercontent.com/aless10/pylings/main/install.sh | bash poetry
```
But I got the following output:
```bash
/usr/local/bin/poetry: line 3: import: command not found
/usr/local/bin/poetry: line 4: import: command not found
/usr/local/bin/poetry: line 5: from: command not found
/usr/local/bin/poetry: poetry: line 7: syntax error near unexpected token `('
/usr/local/bin/poetry: poetry: line 7: `    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3747  100  3747    0     0   9268      0 --:--:-- --:--:-- --:--:--  9367
curl: (23) Failed writing body
```
Then I noticed that the poetry parameter is actually not needed, but the script expects it anyway.

I didn't dig further on this, but I'll try to do it in the next few days and I'll post the outcomes here.

### PR DESCRIPTION
**Pull request by aless10**
fixes #1

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -25,7 +25,11 @@ fi
 
 echo "Checking python 'installer'..."
 
-Installer=$1
+echo "${1-poetry}"
+exit 0
```
Comment (salvatore-giammanco) [inline install.sh:29]: Is this Debug code?

Comment (aless10) [reply install.sh:29]: I forgot to remove it. Thanks

**Review by salvatore-giammanco — APPROVED** [review]
